# Generated by Django 5.1.2 on 2024-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goodsTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_quantity', models.IntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
    ]
