spring:
  application:
    name: shop-service
  liquibase:
    enabled : true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: root
    password: ${PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  app:
    price: 50
    scheduler:
      enabled: false
      optimisation: false

server:
  port: 8080

rest:
  currency:
    host: http://localhost:8081
    methods:
      exchange-rates: /api/v1/currency
  account:
    host: http://localhost:8081
    methods:
      get-account-number: /api/v1/number
  crm:
    host: http://localhost:8081
    methods:
      get-account-inn: /api/v1/crm

  kafka:
    bootstrapServers: localhost:29092
    group-id: group1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE