version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django_admin
      POSTGRES_PASSWORD: 111
      PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - ps

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - ps

networks:
  ps:

volumes:
  postgres_data:


